#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
#ssh -i ~/.ssh/school 35.231.66.168

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp "$1" "$3"@"$2":~/ -i "$4"
fi
