#!/usr/bin/env bash
#  script so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
