#!/usr/bin/env bash
# Shell script to start the SSH conection
#ssh -i ~/.ssh/id_rsa ubuntu@35.231.66.168 ubuntu@54.147.143.45

# Load balancer server name and IP
## lb-01 54.226.190.231

# Install nginx
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World" > sudo /var/www/html/index.html

# Configure Nginx so that its HTTP response contains a custom header
# The name of the custom HTTP header must be "X-Served-By" and the server runnning on
# (Ex:) X-Served-By: 03-web-02
sudo sed -i '29 a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart
sudo service nginx restart
