#!/usr/bin/env bash
# Create a new user for the replica server
# with the host name set to localhost and the password projectcorrection280hbtn
# 2388-web-01 ssh -i ~/.ssh/id_rsa ubuntu@35.243.249.147
# 2388-web-02 ssh -i ~/.ssh/id_rsa ubuntu@54.147.143.45
# lb-01 ssh -i ~/.ssh/id_rsa ubuntu@54.226.190.231

CREATE USER 'replica_user'@'%' IDENTIFIED BY 'password';
# GRANT REPLICATION CLIENT ON *.* TO 'replica_user'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'replica_user'@'%';
GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';
GRANT SELECT ON tyrell_corp.nexus6 TO 'holberton_user'@'localhost';
