#!/usr/bin/env bash
# Script that gives you information about the school file

if [ -e  school ]
then
    if [ -s school ]
    then
        echo "school file is empty"

    elif ! [ -s school ]
    then
        echo "school file is not empty"

    elif [ -f school ] 
    then
        echo "school is a regular file"

    fi

else
    echo "school file does not exist"
fi
