#!/usr/bin/env bash
# Script to set nginx to run as nginx user, and listen to active IPs on port 8000

sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
